/* eslint-disable no-console */
import { existsSync } from 'node:fs';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { posix, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import i18n from '../../../locales/index.js';
import { getRootDir } from '../../../scripts/shared/dir.js';
import { getComponentApi } from '../../../scripts/shared/docs/api.js';
import { getMarkdownTable, parseApiMarkdown } from '../../../scripts/shared/docs/markdown.js';

const { join } = posix;
const __dirname = fileURLToPath(new URL('.', import.meta.url)).replace(/\\/g, '/');
const srcDir = join(__dirname, '../src');
const tsconfig = join(__dirname, '../tsconfig.json');
const managedNotice = [
    '<!--',
    'This file is partially generated by pnpm components:api.',
    'You may edit only the description column; other API columns are refreshed automatically.',
    '-->',
].join('\n');

const getPreviousDescriptions = async outputPath => {
    if (!existsSync(outputPath)) return new Map();

    return parseApiMarkdown(await readFile(outputPath, 'utf8'));
};

const writeApi = async (outputPath, content) => {
    const oldContent = existsSync(outputPath) ? await readFile(outputPath, 'utf8') : '';
    const outputLabel = relative(getRootDir(), outputPath);

    if (oldContent === content) {
        return {
            status: 'unchanged',
            path: outputLabel,
        };
    }

    await writeFile(outputPath, content);

    return {
        status: oldContent ? 'updated' : 'created',
        path: outputLabel,
    };
};

const printResults = results => {
    ['created', 'updated', 'unchanged'].forEach(status => {
        const statusResults = results.filter(result => result.status === status);

        if (statusResults.length === 0) return;

        console.log(`[${status}]:`);
        statusResults.forEach(result => console.log(`  ${result.path}`));
    });
};

const renderApi = (api, previousDescriptions = new Map()) => {
    const content = [];

    api.forEach(({ name, props = [], extendTypes = [], equalType }) => {
        content.push(`### ${name} Props`);
        extendTypes.length && content.push(`> ${i18n.t('extends.from')} \`${extendTypes.join(', ')}\``);
        equalType && content.push(`> ${i18n.t('equal.with')} \`${equalType}\``);
        props.length &&
            content.push(
                getMarkdownTable({
                    headers: [i18n.t('property.name'), i18n.t('description'), i18n.t('type'), i18n.t('default.value')],
                    rows: props.map(prop => [
                        `${prop.name}${prop.optional ? '' : '*'}`,
                        previousDescriptions.get(`${name}.${prop.name}`) || prop.description,
                        { text: prop.type, code: true },
                        { text: prop.defaultValue, code: true },
                    ]),
                }),
            );
    });

    return `${managedNotice}\n\n${content.join('\n\n')}\n`;
};

i18n.setLanguage('zh-CN');

const results = [];

for (const dirent of await readdir(srcDir, { withFileTypes: true })) {
    const direntPath = join(srcDir, dirent.name);
    const entryPoint = join(direntPath, 'index.ts');

    if (!dirent.isDirectory() || dirent.name.startsWith('_') || !existsSync(entryPoint)) continue;

    const api = await getComponentApi({
        entryPoint,
        tsconfig,
        fallbackName: dirent.name
            .split('-')
            .map(part => `${part[0].toUpperCase()}${part.slice(1)}`)
            .join(''),
    });

    if (api.length === 0) continue;

    const outputPath = join(direntPath, 'API.zh-CN.md');
    const previousDescriptions = await getPreviousDescriptions(outputPath);
    const content = renderApi(api, previousDescriptions);

    results.push(await writeApi(outputPath, content));
}

printResults(results);
